---
- name: Eliminacion de Usuarios - Windows
  win_user: 
    name: "{{ item.username }}"
    state: absent
  with_items: 
    - "{{ users }}"

- name: Numero de Caso
  debug: msg="{{ item.case }}"
  with_items: 
    - "{{ users }}"
